version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: yandex_api:${YANDEXAPI_VERSION:-latest}
    restart: always
    env_file:
    - .env
    environment:
      YANDEXAPI_HOST: 0.0.0.0
      YANDEXAPI_DB_FILE: /db_data/db.sqlite3
    volumes:
    - yandex_api-db-data:/db_data/



volumes:
  yandex-api-db-data:
    name: yandex-api-db-data
